/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mp.hello

@SpringBootApplication
class App

fun main(args: Array<String>) {
    SpringApplication.run(Application::class.java, *args)
}
